export const LECTURER_SKILL_TAGS = [
  "Blockchain & hợp đồng thông minh",
  "Điện toán biên (Edge Computing)",
  "Internet vạn vật (IoT)",
  "Thực tế ảo & thực tế tăng cường (VR/AR/MR)",
  "Kỹ thuật an toàn thông tin & bảo mật AI",
  "Phân tích dữ liệu & trực quan hóa",
  "Học máy (Machine Learning)",
  "Học sâu (Deep Learning)",
  "Xử lý ngôn ngữ tự nhiên (NLP)",
  "Thị giác máy tính (Computer Vision)",
  "AI tạo sinh (Generative AI)",
  "Thiết kế & quản trị cơ sở dữ liệu (SQL, NoSQL)",
  "Quản trị hệ điều hành (Windows, Linux, macOS)",
  "Quản trị mạng & an ninh mạng",
  "Điện toán đám mây (AWS, Azure, GCP)",
  "Phát triển Web (Frontend, Backend, Fullstack)",
  "Phát triển ứng dụng di động (Android/iOS/Flutter/React Native)",
  "Phát triển phần mềm nhúng & IoT",
  "Phát triển trò chơi (Game Development)",
  "Nghiên cứu khoa học",
  "Hướng dẫn & cố vấn",
  "Quản lý & học thuật",
  "Phòng thí nghiệm & an toàn",
];
